#!/bin/bash
case "$1" in
  start)
    curl --request POST "http://localhost:9000/crawler" --silent && echo
    ;;
  stop)
    curl --request DELETE "http://localhost:9000/crawler" --silent && echo
    ;;
  *)
    echo "Usage: crawler {start|stop}"
    ;;
esac
