#!/bin/bash
case "$1" in
  switch)
    curl --request POST "http://localhost:9000/index" --silent --show-error && echo
    ;;
  rollback)
    curl --request DELETE "http://localhost:9000/index" --silent --show-error && echo
    ;;
  *)
    echo "Usage: index {switch|rollback}"
    ;;
esac
