#!/bin/bash
case "$1" in
  index)
    curl --request POST --header "Content-Type: application/json" "http://localhost:9000/posts/1377495/comments" --data @`dirname "$0"`/comment.json --silent --show-error && echo
    ;;
  delete)
    curl --request DELETE "http://localhost:9000/posts/1377495/comments/1" --silent --show-error && echo
    ;;
  *)
    echo "Usage: comment {index|delete}"
    ;;
esac
